server:
  port: ${PORT:8083}
  shutdown: graceful

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:appdb}
    username: ${DB_USER:app}
    password: ${DB_PASS:app}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true

  jackson:
    time-zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_schema_history_inventory
    baseline-on-migrate: true
    baseline-version: 0

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

app:
  messaging:
    exchange: order.events
    retryTtlMs: 10000
    queues:
      orderCreated: dev.inventory.order-created
      orderStatusChanged: dev.inventory.order-status-changed
    routing-keys:
      orderCreated: order.created.v1
      orderStatusChanged: order.status-changed.v1
